[package]
name = "rkemu"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
color-print = "0.3.7"
serde = { version = "1.0.216", features = ["derive"] }
serde_yaml = "0.9.34"
