[package]
name = "rk16-asm"
version = "0.1.0"
edition = "2021"

[dependencies]
bimap = "0.6.3"
clap = { version = "4.5.4", features = ["derive"] }
color-print = "0.3.6"
once_cell = "1.19.0"
rk16-arch = { path = "../rk16-arch" }
