[package]
name = "arch"
version = "0.1.0"
edition = "2021"

[dependencies]
bimap = "0.6.3"
num_enum = "0.7.2"
once_cell = "1.19.0"
serde = { version = "1.0.203", features = ["derive"] }
strum = { version = "0.26.2", features = ["derive"] }
